platforms:
  mega2560:
    board: arduino:avr:mega:cpu=atmega2560
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR__
        - __AVR_ATmega2560__
        - ARDUINO_ARCH_AVR
        - ARDUINO_AVR_MEGA2560
        # Why aren't these already provided elsewhere?
        - SS=1
        - MOSI=2
        - MISO=3
        - SCK=4
      warnings:
      flags:

unittest:
    platforms:
        - mega2560
    libraries:
      - "Adafruit BusIO"
      - "Adafruit_MAX31865"
      - "Ethernet"
      - "LiquidCrystal"
      - "RTClib"
      - "SD"

compile:
    platforms:
      - mega2560
    libraries:
      - "Adafruit BusIO"
      - "Adafruit_MAX31865"
      - "Ethernet"
      - "LiquidCrystal"
      - "RTClib"
      - "SD"
