version: 2.1

# orbs:
#   ruby: circleci/ruby@1.0

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - ruby/install-deps # use the ruby orb to install dependencies
      - run:
          name: Install
          command: |
          bundle install
          ./scripts/install_libraries.sh  
          bundle exec arduino_ci_remote.rb


# We use workflows to orchestrate the jobs that we declared above.
workflows:
  version: 2
  build_and_test:     # The name of our workflow is "build_and_test"
    jobs:             # The list of jobs we run as part of this workflow.
      - test:         # Then run test
