# This is the name of the workflow, visible on GitHub UI
name: Arduino CI

# Run on a Push or a Pull Request
on: [push, pull_request]

jobs:
  arduino_ci: 
    runs-on: ubuntu-latest
    steps:
      # Clone the repo using the `checkout` action
      - uses: actions/checkout@v2
      # Use prebuild Arduino-CI
      - uses: Arduino-CI/action@stable-1.x
        env:
          EXPECT_EXAMPLES: true
          EXPECT_UNITTESTS: true
          CUSTOM_INIT_SCRIPT: scripts/install_libraries.sh
