# This is the name of the workflow, visible on GitHub UI
name: Arduino CI

# Run on a Push or a Pull Request
on: [push, pull_request]

jobs:
  runTest: 
    runs-on: ubuntu-latest
    steps:
      # Clone the repo using the `checkout` action
      - uses: actions/checkout@v2

      # Get Ruby and run Arduino CI
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.6

      # Install Arduino IDE and Arduino CI
      - run: |
          bundle install

      # Installing libraries needed for this project
      - name: Install libraries
        run: |
          ./scripts/install_libraries.sh  

      # Finally, run the tests
      - run: |
          bundle exec arduino_ci_remote.rb
